pipeline {
    agent any

    environment {
      KUBECONFIG = '/home/ubuntu/.kube/config'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/monanimals/k8s_conf_monanimal-extranet-web.git'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                // Exemple de commande kubectl, à adapter selon ta config
                sh 'kubectl apply -k dev/'
            }
        }
    }
}
