apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  
namespace: monanimal-extranet-dev
nameSuffix: -dev

patchesStrategicMerge:
  - patchDeployment.yaml
  - patchNamespace.yaml
