apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-monanimal-extranet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-monanimal-extranet
subjects:
  - kind: ServiceAccount
    name: serviceacc-monanimal-extranet