apiVersion: v1
kind: Service
metadata:
  name: service-monanimal-extranet
spec:
  type: ClusterIP
  selector:
    app: monanimal-extranet
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: jmx 
    port: 8080
    targetPort: 8080
