apiVersion: v1
kind: Service
metadata:
  name: service-monanimal-extranet
spec:
  type: ClusterIP
  selector:
    app: monanimal-extranet
  ports:
  - name: htpp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: jmx 
    port: 8080
    targetPort: 8080
