apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base
  
namespace: monanimal-extranet-preprod
nameSuffix: -preprod

patchesStrategicMerge:
  - patchDeployment.yaml
  - patchNamespace.yaml
